import Head from "next/head";
import styles from "../styles/Home.module.css";
import { Canvas } from "@react-three/fiber";
import Box from "../components/threeObject/box";
import CameraPositionController from "../components/cameraPositionController";
import { useState } from "react";

export default function Home() {
  const [cameraX, setCameraX] = useState(0);
  const [cameraY, setCameraY] = useState(0);
  const [cameraZ, setCameraZ] = useState(0);

  return (
    <div className={styles.container}>
      <Head>
        <title>Next.js 3D Object</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>
          Next.js
          <br />
          3D Object
        </h1>
        <div>
          <Canvas camera={{ fov: 75, near: 0.1, far: 20, }}>
            <Box position={[cameraX, cameraY, cameraZ]} />
            <ambientLight intensity={0.5} />
            <spotLight position={[10, 10, 10]} angle={-0.15} penumbra={1} />
            <pointLight position={[-10, -10, -10]} />
          </Canvas>
        </div>
        <CameraPositionController
          cameraX={cameraX}
          cameraY={cameraY}
          cameraZ={cameraZ}
          setCameraX={(cameraX)=>setCameraX(cameraX)}
          setCameraY={(cameraY)=>setCameraY(cameraY)}
          setCameraZ={(cameraZ)=>setCameraZ(cameraZ)}
        />
      </main>
    </div>
  );
}
