import Head from "next/head";
import styles from "../styles/Home.module.css";
import { Canvas } from "@react-three/fiber";
import Box from "../components/threeObject/box";
import BoxPositionController from "../components/boxPositionController";
import { useState } from "react";

export default function Home() {
  const [boxX, setBoxX] = useState(0);
  const [boxY, setBoxY] = useState(0);
  const [boxZ, setBoxZ] = useState(0);

  return (
    <div className={styles.container}>
      <Head>
        <title>Next.js 3D Object</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>
          Next.js
          <br />
          3D Object
        </h1>
        <div>
          <Canvas camera={{ fov: 75, near: 0.1, far: 20, }}>
            <Box position={[boxX, boxY, boxZ]} />
            <ambientLight intensity={0.5} />
            <spotLight position={[10, 10, 10]} angle={-0.15} penumbra={1} />
            <pointLight position={[-10, -10, -10]} />
          </Canvas>
        </div>
        <BoxPositionController
          boxX={boxX}
          boxY={boxY}
          boxZ={boxZ}
          setBoxX={(boxX)=>setBoxX(boxX)}
          setBoxY={(boxY)=>setBoxY(boxY)}
          setBoxZ={(boxZ)=>setBoxZ(boxZ)}
        />
      </main>
    </div>
  );
}
